logging:
  level:
    - logging.level.org.springframework.web: warn
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  datasource:
    url: jdbc:postgresql://localhost:5432/sworhm
    username: sworhm
    password: sworhmpw
sworhm:
  security:
    cors:
      config:
        allowed-origins:
          - https://marmer.online
          - http://marmer.online
          - https://marmer.github.io
          - http://marmer.github.io
          - https://localhost
          - http://localhost
          - http://localhost:3000
        allow-credentials: true