logging:
  level:
    - logging.level.org.springframework.web: warn
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  datasource:
    url: jdbc:postgresql://localhost:5432/sworhm
    username: sworhm
    password: sworhmpw
