version: '3.3'

services:
  db:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_USER: sworhm
      POSTGRES_PASSWORD: sworhmpw
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - sworhm-db-volume:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432

volumes:
  sworhm-db-volume:
